-- --- INIZIO RESET DATABASE ---
-- Disabilita temporaneamente i vincoli di chiave esterna per cancellare senza errori
SET FOREIGN_KEY_CHECKS = 0;

-- Cancellazione tabelle (l'ordine qui non conta grazie a FOREIGN_KEY_CHECKS = 0)
DROP TABLE IF EXISTS ALLEGATO;
DROP TABLE IF EXISTS RISPOSTA;
DROP TABLE IF EXISTS INIZIATIVA_SALVATA;
DROP TABLE IF EXISTS FIRMA_INIZIATIVA;
DROP TABLE IF EXISTS VOTI_BILANCIO;
DROP TABLE IF EXISTS OPZIONI_BILANCIO;
DROP TABLE IF EXISTS iniziativa;
DROP TABLE IF EXISTS BILANCIO_PARTECIPATIVO;
DROP TABLE IF EXISTS NOTIFICA;
DROP TABLE IF EXISTS PRE_AUTORIZZATO;
DROP TABLE IF EXISTS UTENTE;db
DROP TABLE IF EXISTS PIATTAFORMA;
DROP TABLE IF EXISTS CATEGORIA;

-- Riabilita i vincoli di chiave esterna
SET FOREIGN_KEY_CHECKS = 1;
-- --- FINE RESET DATABASE ---


-- Creazione Tabelle Indipendenti (Livello 0)

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PIATTAFORMA (
    ID_PIATTAFORMA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PIATTAFORMA VARCHAR(100) NOT NULL,
    PATH_ICONA VARCHAR(255),
    LINK_BASE_PIATTAFORMA VARCHAR(255)
);

CREATE TABLE UTENTE (
    ID_UTENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    COGNOME VARCHAR(100) NOT NULL,
    CODICE_FISCALE CHAR(16) NOT NULL UNIQUE,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    IS_ADMIN BOOLEAN DEFAULT FALSE,
    IS_CITTADINO BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Creazione Tabelle Livello 1 (Dipendono da Utente)

CREATE TABLE PRE_AUTORIZZATO (
    CODICE_FISCALE CHAR(16) PRIMARY KEY,
    DATA_INSERIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    INSERITO_DA INT NOT NULL,
    FOREIGN KEY (INSERITO_DA) REFERENCES UTENTE(ID_UTENTE)
);

CREATE TABLE NOTIFICA (
    ID_NOTIFICA INT AUTO_INCREMENT PRIMARY KEY,
    ID_UTENTE INT NOT NULL,
    TESTO TEXT NOT NULL,
    LETTA BOOLEAN DEFAULT FALSE,
    DATA_CREAZIONE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    LINK_RIF VARCHAR(255),
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID_UTENTE) ON DELETE CASCADE
);

CREATE TABLE BILANCIO_PARTECIPATIVO (
    ID_BIL INT AUTO_INCREMENT PRIMARY KEY,
    ID_CREATOR INT NOT NULL,
    TITOLO VARCHAR(200) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    DATA_SCADENZA DATE NOT NULL,
    FOREIGN KEY (ID_CREATOR) REFERENCES UTENTE(ID_UTENTE)
);

-- Creazione Tabelle Livello 2

CREATE TABLE INIZIATIVA (
    ID_INIZIATIVA INT AUTO_INCREMENT PRIMARY KEY,
    TITOLO VARCHAR(255) NOT NULL,
    DESCRIZIONE TEXT NOT NULL,
    LUOGO VARCHAR(64),
    STATO ENUM('In corso', 'Approvata', 'Respinta', 'Scaduta', 'Archiviata') DEFAULT 'In corso',
    NUM_FIRME INT DEFAULT 0,
    DATA_CREAZIONE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    DATA_SCADENZA DATE,
    
    -- Chiavi Esterne
    ID_AUTORE INT,
    ID_CATEGORIA INT NOT NULL,
    ID_PIATTAFORMA INT,
    
    -- Gestione iniziativa esterna
    URL_ESTERNO VARCHAR(500), 

    FOREIGN KEY (ID_AUTORE) REFERENCES UTENTE(ID_UTENTE) ON DELETE SET NULL,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
    FOREIGN KEY (ID_PIATTAFORMA) REFERENCES PIATTAFORMA(ID_PIATTAFORMA)
);

CREATE TABLE OPZIONI_BILANCIO (
    ID_OB INT AUTO_INCREMENT PRIMARY KEY,
    ID_BIL INT NOT NULL,
    TEXT VARCHAR(250) NOT NULL,
    POSITION TINYINT NOT NULL,
    FOREIGN KEY (ID_BIL) REFERENCES BILANCIO_PARTECIPATIVO(ID_BIL) ON DELETE CASCADE
);

-- Creazione Tabelle Livello 3

CREATE TABLE VOTI_BILANCIO (
    ID_UTENTE INT NOT NULL,
    ID_BIL INT NOT NULL,
    OPTION_ID INT NOT NULL,
    VOTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID_UTENTE, ID_BIL),
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID_UTENTE),
    FOREIGN KEY (ID_BIL) REFERENCES BILANCIO_PARTECIPATIVO(ID_BIL),
    FOREIGN KEY (OPTION_ID) REFERENCES OPZIONI_BILANCIO(ID_OB)
);

CREATE TABLE FIRMA_INIZIATIVA (
    ID_UTENTE INT NOT NULL,
    ID_INIZIATIVA INT NOT NULL,
    DATA_FIRMA TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID_UTENTE, ID_INIZIATIVA),
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID_UTENTE),
    FOREIGN KEY (ID_INIZIATIVA) REFERENCES INIZIATIVA(ID_INIZIATIVA)
);

CREATE TABLE INIZIATIVA_SALVATA (
    ID_UTENTE INT NOT NULL,
    ID_INIZIATIVA INT NOT NULL,
    SAVED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID_UTENTE, ID_INIZIATIVA),
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID_UTENTE),
    FOREIGN KEY (ID_INIZIATIVA) REFERENCES INIZIATIVA(ID_INIZIATIVA)
);

CREATE TABLE RISPOSTA (
    ID_RISPOSTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_INIZIATIVA INT NOT NULL,
    ID_ADMIN INT,
    TEXT_RISP TEXT NOT NULL,
    DATA_CREAZIONE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (ID_INIZIATIVA) REFERENCES INIZIATIVA(ID_INIZIATIVA) ON DELETE CASCADE,
    FOREIGN KEY (ID_ADMIN) REFERENCES UTENTE(ID_UTENTE) ON DELETE SET NULL
);

-- Creazione Tabelle Livello 4

CREATE TABLE ALLEGATO (
    ID_ALLEGATO INT AUTO_INCREMENT PRIMARY KEY,
    FILE_NAME VARCHAR(255) NOT NULL,
    FILE_PATH VARCHAR(500) NOT NULL,
    FILE_TYPE VARCHAR(50),
    UPLOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    
    ID_INIZIATIVA INT,
    ID_RISPOSTA INT,
    
    FOREIGN KEY (ID_INIZIATIVA) REFERENCES INIZIATIVA(ID_INIZIATIVA) ON DELETE CASCADE,
    FOREIGN KEY (ID_RISPOSTA) REFERENCES RISPOSTA(ID_RISPOSTA) ON DELETE CASCADE,

    CONSTRAINT CHK_Allegato_XOR CHECK (
        (ID_INIZIATIVA IS NOT NULL AND ID_RISPOSTA IS NULL) OR 
        (ID_INIZIATIVA IS NULL AND ID_RISPOSTA IS NOT NULL)
    )
);